conn = getDBConnection();
csvs = dir('D:/GitHub/Manual-Classify/python/tools/annotations_csv_May2017/*.csv');

query = 'SELECT id FROM classify_timeseries WHERE url = ''http://ifcb-data.whoi.edu/mvco/'';';
cursor = exec(conn, query);
cursor = fetch(cursor);
result = cursor.Data{1,1}{1};

query = [sprintf('ALTER TABLE classify_classification ALTER COLUMN timeseries_id SET DEFAULT ''%s'', ', result) ...
    'ALTER COLUMN user_id SET DEFAULT 1, ' ...
    'ALTER COLUMN time SET DEFAULT now(), ' ...
    'ALTER COLUMN level SET DEFAULT 1, ' ...
    'ALTER COLUMN verifications SET DEFAULT 0;'];
exec(conn, query);

query = [sprintf('ALTER TABLE classify_tag ALTER column timeseries_id SET DEFAULT ''%s'', ', result) ...
    'ALTER COLUMN user_id SET DEFAULT 1, ' ...
    'ALTER COLUMN time SET DEFAULT now(), ' ...
    'ALTER COLUMN level SET DEFAULT 1, ' ...
    'ALTER COLUMN verifications SET DEFAULT 0, ' ...
    'ALTER COLUMN negation SET DEFAULT false;'];
exec(conn, query);

for csv = csvs'
    name = strrep(csv.name, '.csv', '');
    insertData4(conn, name, sprintf('%s\\%s', csv.folder, csv.name));
end

query = ['ALTER TABLE classify_classification ALTER COLUMN timeseries_id DROP DEFAULT, ' ...
    'ALTER COLUMN user_id DROP DEFAULT, ' ...
    'ALTER COLUMN time DROP DEFAULT, ' ...
    'ALTER COLUMN level DROP DEFAULT, ' ...
    'ALTER COLUMN verifications DROP DEFAULT;'];
exec(conn, query);

query = ['ALTER TABLE classify_tag ALTER COLUMN timeseries_id DROP DEFAULT, ' ...
	'ALTER COLUMN user_id DROP DEFAULT, ' ...
	'ALTER COLUMN time DROP DEFAULT, ' ...
	'ALTER COLUMN level DROP DEFAULT, ' ...
    'ALTER COLUMN verifications DROP DEFAULT, ' ...
    'ALTER COLUMN negation DROP DEFAULT;'];
exec(conn, query);