# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=100)),
                ('roi', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('classification_id', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('verifications', models.IntegerField(default=0)),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('timeseries_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('international_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=100)),
                ('roi', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tag_id', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('verifications', models.IntegerField(default=0)),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('timeseries_id', models.CharField(max_length=36)),
                ('negation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Timeseries',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('bin', 'roi', 'user_id', 'tag_id', 'negation')]),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together=set([('bin', 'roi', 'user_id', 'classification_id')]),
        ),
    ]
