# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['bin'], name='classify_cl_bin_60d347_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_id'], name='classify_ta_tag_id_8c2a64_idx'),
        ),
    ]
