# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 19:26
from __future__ import unicode_literals

from django.db import migrations


CREATE_VIEWS = """
create materialized view classify_user_power as
select u.id as user_id, max(g.power) as "power"
from auth_user u, auth_group g, auth_user_groups ugs
where u.id = ugs.user_id
and g.id = ugs.group_id
group by u.id
order by u.id;

create or replace function refresh_user_power()
returns trigger language plpgsql
as $$
begin
    refresh materialized view classify_user_power;
    return null;
end $$;

create trigger refresh_user_power
after insert or update or delete or truncate
on auth_user for each statement 
execute procedure refresh_user_power();

create trigger refresh_user_power
after insert or update or delete or truncate
on auth_group for each statement 
execute procedure refresh_user_power();

create trigger refresh_user_power
after insert or update or delete or truncate
on auth_user_groups for each statement 
execute procedure refresh_user_power();

create or replace view classify_winning_class as
select distinct on (bin, roi) bin, roi, user_id, "time", classification_id, "level", verifications, verification_time, timeseries_id, (
    select "power" from classify_user_power cup
    where cup.user_id = cc.user_id
) user_power
from classify_classification cc
order by bin, roi, user_power desc, "time" desc;
"""

DROP_VIEWS = """
drop view classify_winning_class;
drop materialized view classify_user_power;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_bin_tag_indexes'),
    ]

    operations = [
        migrations.RunSQL(CREATE_VIEWS, DROP_VIEWS)
    ]
