# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 21:26
from __future__ import unicode_literals

from django.db import migrations

CREATE_VIEW = """
 create view classify_counts_by_bin as
 SELECT bin, classification_id,
    count(*) AS count,
    ( SELECT ts.url
           FROM classify_timeseries ts
          WHERE ts.id::varchar = timeseries_id) AS timeseries_url
   FROM classify_winning_class
   group by timeseries_id, bin, classification_id
   order by timeseries_id, bin, classification_id;
"""

DROP_VIEW = """
drop view classify_counts_by_bin;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_summary_views'),
    ]

    operations = [
        migrations.RunSQL(CREATE_VIEW, DROP_VIEW)
    ]
